version: "3.8"
services:
  catalog-service:
    depends_on:
      - luckycardshop
    image: "catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://luckycardshop:5432/luckycardshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  luckycardshop:
    image: "postgres:latest"
    container_name: "luckycardshop"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  luckycardshop-redis:
    image: "redis:7.0"
    container_name: "luckycardshop-redis"
    ports:
      - 6379:6379
  luckycardshop-rabbitmq:
    image: rabbitmq:management
    container_name: luckycardshop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  luckycardshop-keycloak:
    image: quay.io/keycloak/keycloak
    container_name: "luckycardshop-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
  luckycardshop-ui:
    image: "ghcr.io/luckycardshop/luckycardshop-ui:v1"
    container_name: "luckycardshop-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004