apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: luckycardshop
data:
  init.sql: |
    CREATE DATABASE luckycardshopdb_catalog;
    CREATE DATABASE luckycardshop_order;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckycardshop
  labels:
    db: luckycardshop
spec:
  selector:
    matchLabels:
      db: luckycardshop
  template:
    metadata:
      labels:
        db: luckycardshop
    spec:
      containers:
        - name: luckycardshop
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
            - name: POSTGRES_DB
              value: luckycardshopdb_catalog
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
---

apiVersion: v1
kind: Service
metadata:
  name: luckycardshop
  labels:
    db: luckycardshop
spec:
  type: ClusterIP
  selector:
    db: luckycardshop
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
